# Generated by Django 4.2.9 on 2024-01-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_alter_library_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=1000)),
                ('libraries_id', models.ManyToManyField(blank=True, related_name='books', to='libraries.library')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
